export const waccaSongs = {
//layout taken/tweaked from WACCA WebUI GitHub https://github.com/Stabyourself/mithical/  
    song1: {
      id: 3,
      title: "Rainbow Dream",
      titleEnglish: "test",
      artist: "DJ Genki feat. Yukacco",
      gameVersion: 1,
      bpm: 180,
      imageName: "3.png",
      audioPath: "3.wav",
      category: "TANO*C (Original)",
      releaseDate: "2019-07-17",
      sheets: [
        {
          difficulty: 3,
          gameVersion: 1,
          charter: "Marvelous",
        },
        {
          difficulty: 8.7,
          gameVersion: 1,
          charter: "Marvelous",
        },
        {
          difficulty: 11.4,
          gameVersion: 1,
          charter: "Marvelous",
        },
      ],
    },
    song2: {
        id: 4,
        title: "Knight Rider",
        titleEnglish: null,
        artist: "USAO",
        gameVersion: 1,
        bpm: 200,
        imageName: "4.png",
        audioPath: "4.wav",
        category: "TANO*C (Original)",
        releaseDate: "2019-07-17",
        sheets: [
          {
            difficulty: 6,
            gameVersion: 1,
            charter: "Marvelous",
          },
          {
            difficulty: 10.9,
            gameVersion: 1,
            charter: "Marvelous",
          },
          {
            difficulty: 13.3,
            gameVersion: 1,
            charter: "Marvelous",
          },
        ],
      },
      song3: {
        id: 32,
        title: "Let you DIVE!",
        titleEnglish: null,
        artist: "HARDCORE TANO*C & エリザベス（CV:大西沙織）",
        gameVersion: 1,
        bpm: 185,
        imageName: "32.png",
        audioPath: "32.wav",
        audioInfPath: "32_I.wav",
        category: "Original",
        releaseDate: "2019-07-17",
        sheets: [
          {
            difficulty: 3,
            gameVersion: 1,
            charter: "Marvelous",
          },
          {
            difficulty: 9.7,
            gameVersion: 1,
            charter: "Marvelous",
          },
          {
            difficulty: 11.8,
            gameVersion: 1,
            charter: "Marvelous",
          },
          {
            difficulty: 13.4,
            gameVersion: 4,
            charter: "Marvelous",
          },
        ],
      },
      song4: {
        id: 2012,
        title: "with U",
        titleEnglish: null,
        artist: "t+pazolite & Massive New Krew feat. リリィ(CV:青木志貴)",
        gameVersion: 3,
        bpm: 155,
        imageName: "2012.png",
        audioPath: "2012.wav",
        category: "Original",
        releaseDate: "2020-09-16",
        sheets: [
          {
            difficulty: 3,
            gameVersion: 3,
            charter: "Marvelous",
          },
          {
            difficulty: 7.9,
            gameVersion: 3,
            charter: "Marvelous",
          },
          {
            difficulty: 11.8,
            gameVersion: 3,
            charter: "Marvelous",
          },
          {
            difficulty: 13.6,
            gameVersion: 3,
            charter: "Marvelous",
          },
        ],
      },
      song5: {
        id: 3011,
        title: "Ouvertüre",
        titleEnglish: null,
        artist: "USAO & DJ Genki feat. ルーン(CV:河瀬茉希)",
        gameVersion: 5,
        bpm: 200,
        imageName: "3011.png",
        audioPath: "3011.wav",
        audioInfPath: "3011_I.wav",
        category: "Original",
        releaseDate: "2021-08-09",
        sheets: [
          {
            difficulty: 3,
            gameVersion: 5,
            charter: "Marvelous",
          },
          {
            difficulty: 9.6,
            gameVersion: 5,
            charter: "Marvelous",
          },
          {
            difficulty: 13.3,
            gameVersion: 5,
            charter: "Marvelous",
          },
          {
            difficulty: 14,
            gameVersion: 5,
            charter: "Marvelous",
          },
        ],
      },
      song3064: {
        id: 3064,
        title: "DIVE With Ü",
        titleEnglish: null,
        artist:
          "HARDCORE TANO*C & エリザベス（CV:大西沙織） & リリィ（CV:青木志貴） & ルーン（CV:河瀬茉希）",
        gameVersion: 5,
        bpm: 180,
        imageName: "3064.png",
        audioPath: "3064.wav",
        category: "Original",
        releaseDate: "2022-07-17",
        sheets: [
          {
            difficulty: 3,
            gameVersion: 5,
            charter: "Marvelous",
          },
          {
            difficulty: 9.6,
            gameVersion: 5,
            charter: "Marvelous",
          },
          {
            difficulty: 13.3,
            gameVersion: 5,
            charter: "Marvelous",
          },
          {
            difficulty: 12,
            gameVersion: 5,
            charter: "Marvelous",
          },
        ],
      },
    }
